name: TopServerRewards
version: 1.2.1
main: pl.topserver.rewards.TopServerRewards
api-version: 1.20
author: TopServer.pl
description: Plugin do odbierania nagród za głosy z TopServer.pl

commands:
  ts:
    description: Odbierz nagrodę za głos na TopServer.pl
    usage: /ts odbierz
    aliases: [topserver, tsreward]

permissions:
  topserver.claim:
    description: Pozwala na odbieranie nagród
    default: true
  topserver.admin:
    description: Dostęp do komend administracyjnych
    default: op